# Generated by Django 4.2.16 on 2024-11-29 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(1994, 1, 1)),
        ),
    ]
