# Generated by Django 4.2.16 on 2024-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
