# Generated by Django 4.2.16 on 2024-12-04 21:41

import CoreApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[CoreApp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile-pics/keyd.jpg', upload_to='images/profile-pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), CoreApp.models.max_file_size_validator]),
        ),
    ]
