# Generated by Django 4.2.16 on 2024-12-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_alter_userprofile_profile_picture_userinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('comment', 'Comment'), ('profile', 'Profile')], max_length=10, verbose_name='Report Type')),
                ('reason', models.TextField(max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed Status')),
                ('reported_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='CoreApp.comment', verbose_name='Reported Comment')),
                ('reported_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports', to='CoreApp.userprofile', verbose_name='Reported Profile')),
                ('user_reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='CoreApp.userprofile', verbose_name='Reporting User')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'Core_Reports',
            },
        ),
    ]
