# Generated by Django 4.2.16 on 2024-11-26 20:18

import CoreApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Core_Categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Başında 0 olmadan, geçerli bir telefon numarassı girin.', regex='^\\d{10}')])),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(blank=True, default=CoreApp.models.generate_random_unique_id, max_length=10, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='images/profile-pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), CoreApp.models.max_file_size_validator])),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('max_otp_try', models.PositiveIntegerField(default=3)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='CoreApp.userprofile')),
                ('following', models.ManyToManyField(blank=True, related_name='follows', to='CoreApp.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'Core_Users',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_positive', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CoreApp.category')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_comments', to='CoreApp.userprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='CoreApp.userprofile')),
                ('profile_commented_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='CoreApp.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CoreApp.userprofile')),
            ],
            options={
                'db_table': 'Core_Comments',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='CoreApp.userprofile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='CoreApp.userprofile')),
            ],
            options={
                'db_table': 'Core_Follows',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
