# Generated by Django 4.2.16 on 2024-12-04 21:53

import CoreApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_alter_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/images/profile-pics/keyd.jpg', upload_to='images/profile-pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), CoreApp.models.max_file_size_validator]),
        ),
    ]
