# Generated by Django 5.1.4 on 2024-12-17 22:33

import CoreApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(max_length=255, verbose_name='Gerekçe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('profile', 'Profile')], max_length=10, verbose_name='Şikayet Türü'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='CoreApp.comment', verbose_name='Şikayet Edilen Yorum'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports', to='CoreApp.userprofile', verbose_name='Şikayet Edilen Profil'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_reporting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='CoreApp.userprofile', verbose_name='Rapor Eden Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[CoreApp.models.validate_phone_number]),
        ),
    ]
