# Generated by Django 5.1.4 on 2024-12-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0008_comment_category_scores_alter_report_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
